import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { stripe, PRICE_IDS, type PlanId } from "@/lib/stripe/client";
import { verifyAuthToken } from "@/lib/firebase/auth";
import { adminDb } from "@/lib/firebase/admin";
import { FieldValue } from "firebase-admin/firestore";

const CheckoutSchema = z.object({
  plan: z.enum(["pro", "premium"]),
  // ISO 8601 timestamp generated by the client at the moment both consent
  // checkboxes are ticked and the checkout button is clicked.
  consentTimestamp: z.string().datetime(),
});

export async function POST(request: NextRequest) {
  const decoded = await verifyAuthToken(request);
  if (!decoded) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "invalid_json" }, { status: 400 });
  }

  const parsed = CheckoutSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "invalid_plan" }, { status: 400 });
  }

  const plan: PlanId = parsed.data.plan;
  const { consentTimestamp } = parsed.data;
  const priceId = PRICE_IDS[plan];

  if (!priceId) {
    return NextResponse.json(
      { error: "price_not_configured" },
      { status: 500 },
    );
  }

  // Best-effort IP for the PTAC audit trail. Vercel sets x-forwarded-for;
  // fall back to x-real-ip, then mark as unknown if neither is present.
  const ip =
    request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
    request.headers.get("x-real-ip") ??
    "unknown";

  // Store the digital-content consent record in Firestore before creating the
  // Stripe session. If the session creation fails the record is a no-op;
  // if the user disputes later this document is the primary audit evidence.
  const userRef = adminDb.collection("users").doc(decoded.uid);
  const consentRecord = {
    timestamp: consentTimestamp,
    ip,
    checkboxes: ["immediate_delivery", "withdrawal_waiver"],
  };

  await userRef.set(
    { digitalContentConsent: consentRecord },
    { merge: true },
  );

  // Also write to a dedicated sub-collection so the record is immutable even
  // if the user profile is later updated or deleted.
  await adminDb
    .collection("withdrawalConsents")
    .doc(`${decoded.uid}_${plan}_${Date.now()}`)
    .set({
      uid: decoded.uid,
      email: decoded.email ?? null,
      plan,
      ...consentRecord,
      createdAt: FieldValue.serverTimestamp(),
    });

  // Check if user already has a Stripe customer ID
  const userDoc = await userRef.get();
  const userData = userDoc.exists
    ? (userDoc.data() as Record<string, unknown>)
    : {};
  const existingCustomerId = userData.stripeCustomerId as string | undefined;

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  const sessionParams: Record<string, unknown> = {
    mode: "subscription",
    payment_method_types: ["card"],
    line_items: [{ price: priceId, quantity: 1 }],
    success_url: `${appUrl}/payment/success?session_id={CHECKOUT_SESSION_ID}`,
    cancel_url: `${appUrl}/payment/cancel`,
    metadata: {
      firebaseUid: decoded.uid,
      plan,
      // Stored in Stripe for dispute resolution — PTAC requires proof that the
      // consumer explicitly waived their 14-day withdrawal right before purchase.
      withdrawal_waiver_consent: "true",
      consent_timestamp: consentTimestamp,
      consent_ip: ip,
    },
  };

  if (existingCustomerId) {
    sessionParams.customer = existingCustomerId;
  } else {
    sessionParams.customer_email = decoded.email ?? undefined;
  }

  let session: Awaited<ReturnType<typeof stripe.checkout.sessions.create>>;
  try {
    session = await stripe.checkout.sessions.create(
      sessionParams as Parameters<typeof stripe.checkout.sessions.create>[0],
    );
  } catch (err) {
    console.error("[stripe/checkout] Stripe error:", err);
    return NextResponse.json(
      { error: "stripe_error", detail: String(err) },
      { status: 500 },
    );
  }

  return NextResponse.json({ url: session.url });
}
