import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { stripe, getPriceId, type PlanId, type BillingInterval } from "@/lib/stripe/client";
import { verifyAuthToken } from "@/lib/firebase/auth";
import { adminDb } from "@/lib/firebase/admin";
import { FieldValue } from "firebase-admin/firestore";

const CheckoutSchema = z.object({
  plan: z.enum(["pro", "premium"]),
  interval: z.enum(["monthly", "annual"]).default("monthly"),
  // ISO 8601 timestamp generated by the client at the moment both consent
  // checkboxes are ticked and the checkout button is clicked.
  consentTimestamp: z.string().datetime(),
  // Optional affiliate/influencer promo code
  affiliateCode: z.string().min(1).max(20).optional(),
});

export async function POST(request: NextRequest) {
  if (!process.env.STRIPE_SECRET_KEY) {
    console.error("[stripe/checkout] STRIPE_SECRET_KEY is not set");
    return NextResponse.json({ error: "stripe_not_configured" }, { status: 500 });
  }

  const decoded = await verifyAuthToken(request);
  if (!decoded) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "invalid_json" }, { status: 400 });
  }

  const parsed = CheckoutSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "invalid_plan" }, { status: 400 });
  }

  const plan: PlanId = parsed.data.plan;
  const interval: BillingInterval = parsed.data.interval;
  const { consentTimestamp, affiliateCode } = parsed.data;
  const priceId = getPriceId(plan, interval);

  if (!priceId) {
    console.error(
      `[stripe/checkout] Missing price ID for plan "${plan}" interval "${interval}". ` +
        `Check STRIPE_PRICE_* and STRIPE_*_ANNUAL_PRICE_ID env vars in Vercel.`,
    );
    return NextResponse.json({ error: "price_not_configured" }, { status: 500 });
  }

  // Best-effort IP for the PTAC audit trail. Vercel sets x-forwarded-for;
  // fall back to x-real-ip, then mark as unknown if neither is present.
  const ip =
    request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
    request.headers.get("x-real-ip") ??
    "unknown";

  // Store the digital-content consent record in Firestore before creating the
  // Stripe session. If the session creation fails the record is a no-op;
  // if the user disputes later this document is the primary audit evidence.
  const userRef = adminDb.collection("users").doc(decoded.uid);
  const consentRecord = {
    timestamp: consentTimestamp,
    ip,
    checkboxes: ["immediate_delivery", "withdrawal_waiver"],
  };

  try {
    await userRef.set(
      { digitalContentConsent: consentRecord },
      { merge: true },
    );

    // Also write to a dedicated sub-collection so the record is immutable even
    // if the user profile is later updated or deleted.
    await adminDb
      .collection("withdrawalConsents")
      .doc(`${decoded.uid}_${plan}_${Date.now()}`)
      .set({
        uid: decoded.uid,
        email: decoded.email ?? null,
        plan,
        ...consentRecord,
        createdAt: FieldValue.serverTimestamp(),
      });
  } catch (err) {
    console.error("[stripe/checkout] Firestore consent write failed:", err);
    return NextResponse.json(
      { error: "consent_write_failed" },
      { status: 500 },
    );
  }

  // Check if user already has a Stripe customer ID
  let userData: Record<string, unknown> = {};
  try {
    const userDoc = await userRef.get();
    userData = userDoc.exists ? (userDoc.data() as Record<string, unknown>) : {};
  } catch (err) {
    console.error("[stripe/checkout] Failed to fetch user doc:", err);
    return NextResponse.json({ error: "user_lookup_failed" }, { status: 500 });
  }
  const existingCustomerId = userData.stripeCustomerId as string | undefined;

  // Resolve affiliate code: prefer the one passed explicitly, fall back to what's stored on the user
  const resolvedAffiliateCode =
    (affiliateCode ?? (userData.affiliateCode as string | undefined))?.toUpperCase().trim() ?? null;

  // Look up the affiliate code and get its Stripe coupon ID.
  // Non-fatal: a missing/invalid code must never block a paid upgrade.
  let stripeCouponId: string | null = null;
  if (resolvedAffiliateCode) {
    try {
      const codeSnap = await adminDb.collection("affiliateCodes").doc(resolvedAffiliateCode).get();
      if (codeSnap.exists) {
        const codeData = codeSnap.data() as Record<string, unknown>;
        if (codeData.active && codeData.stripeCouponId) {
          stripeCouponId = codeData.stripeCouponId as string;
        }
      }
    } catch (err) {
      // Degrade gracefully — continue without a discount rather than blocking checkout
      console.error("[stripe/checkout] Affiliate code lookup failed (proceeding without discount):", err);
    }
  }

  // NEXT_PUBLIC_APP_URL must be set in production. The localhost fallback is
  // only valid for local dev; Stripe live mode rejects non-HTTPS callback URLs.
  const appUrl = process.env.NEXT_PUBLIC_APP_URL;
  if (!appUrl) {
    const isLocal = process.env.NODE_ENV === "development";
    if (!isLocal) {
      console.error("[stripe/checkout] NEXT_PUBLIC_APP_URL is not set — cannot build valid callback URLs for Stripe");
      return NextResponse.json({ error: "app_url_not_configured" }, { status: 500 });
    }
  }
  const resolvedAppUrl = appUrl ?? "http://localhost:3000";

  const sessionParams: Record<string, unknown> = {
    mode: "subscription",
    payment_method_types: ["card"],
    line_items: [{ price: priceId, quantity: 1 }],
    success_url: `${resolvedAppUrl}/payment/success?session_id={CHECKOUT_SESSION_ID}&plan=${plan}&interval=${interval}`,
    cancel_url: `${resolvedAppUrl}/payment/cancel?plan=${encodeURIComponent(plan)}&interval=${encodeURIComponent(interval)}`,
    metadata: {
      firebaseUid: decoded.uid,
      plan,
      interval,
      // Stored in Stripe for dispute resolution — PTAC requires proof that the
      // consumer explicitly waived their 14-day withdrawal right before purchase.
      withdrawal_waiver_consent: "true",
      consent_timestamp: consentTimestamp,
      consent_ip: ip,
      ...(resolvedAffiliateCode ? { affiliateCode: resolvedAffiliateCode } : {}),
    },
  };

  // Apply affiliate discount coupon if one was found
  if (stripeCouponId) {
    sessionParams.discounts = [{ coupon: stripeCouponId }];
  }

  if (existingCustomerId) {
    sessionParams.customer = existingCustomerId;
  } else {
    sessionParams.customer_email = decoded.email ?? undefined;
  }

  let session: Awaited<ReturnType<typeof stripe.checkout.sessions.create>>;
  try {
    session = await stripe.checkout.sessions.create(
      sessionParams as Parameters<typeof stripe.checkout.sessions.create>[0],
    );
  } catch (err) {
    console.error("[stripe/checkout] Stripe error:", err);
    return NextResponse.json(
      { error: "stripe_error" },
      { status: 500 },
    );
  }

  return NextResponse.json({ url: session.url });
}
